world_origin:

  units: "LATLON" # {"UTM, "LATLON"}

  origin_x: 50.0764041
  origin_y: 14.4180359

safety_area:

  enabled: true

  horizontal:

    # the frame of reference in which the points are expressed
    frame_name: "local_origin"

    # polygon
    #
    # x, y [m] for any frame_name except latlon_origin
    # x = latitude, y = longitude [deg]  for frame_name=="latlon_origin"
    points: [
      -10, -10,
      10, -10,
      10, 10,
      -10, 10,
    ]

  vertical:

    # the frame of reference in which the max&min z is expressed
    frame_name: "local_origin"

    max_z: 10.0
    min_z: -10.0
