mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    # available in mrs_uav_state_estimators: gps_garmin, gps_baro, rtk, aloam, ground_truth, dummy
    state_estimators: [
    # "gps_baro",
    "open_vins",
    # "vins_kickoff",
    ]

    initial_state_estimator: "open_vins" # will be used as the first state estimator
