volumes:

  shared_data:

  uav_configs:

  bag_files:

services:

  # will copy data shared between containers form the shared_data container to the shared volume
  shared_data:
    image: klaxalk:5000/robofly:shared_data
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    command: sh -c "rm -rvf /etc/ctu-mrs/shared_data/*; mkdir -pv /etc/ctu-mrs/shared_data; cp -rv /etc/shared_data/* /etc/ctu-mrs/shared_data/"

  uav_configs:
    image: fly4future/uav_configs:robofly_00001
    volumes:
      - uav_configs:/etc/fly4future/uav_configs:consistent
    command: sh -c "rm -rvf /etc/fly4future/uav_configs/*; mkdir -pv /etc/fly4future/uav_configs; cp -rv /etc/uav_configs/* /etc/fly4future/uav_configs/"

  ros-master:
    image: ctumrs/mrs_uav_system:robofly
    network_mode: host
    depends_on:
      - shared_data
    env_file:
      - ./stack.env
    command: roscore

  ros-time:
    image: ctumrs/mrs_uav_system:robofly
    network_mode: host
    depends_on:
      - ros-master
    env_file:
      - ./stack.env
    command: bash -c "waitForRos && rosparam set use_sim_time false && read"

  sensors:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
      - /dev/:/dev/
    privileged: true
    env_file:
      - ./stack.env
    command: bash -c "waitForTime && roslaunch mrs_uav_deployment sensors.launch"

  hw_api:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    env_file:
      - ./stack.env
    command: bash -c "waitForTime && roslaunch mrs_uav_px4_api api.launch"

  uav_core:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    env_file:
      - ./stack.env
    command: bash -c "waitForHw && roslaunch mrs_uav_core core.launch platform_config:=`rospack find mrs_robofly_core`/config/platform_config.yaml custom_config:=/etc/ctu-mrs/shared_data/custom_config.yaml world_config:=/etc/ctu-mrs/shared_data/world_local.yaml network_config:=/etc/ctu-mrs/shared_data/network_config.yaml"

  vio_cam:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
      - uav_configs:/etc/fly4future/uav_configs:consistent
    devices:
      - /dev/:/dev/
    privileged: true
    env_file:
      - ./stack.env
    command: bash -c "waitForTime && roslaunch libcamera_ros_driver uav.launch standalone:=false camera_name:=down config:=/etc/fly4future/uav_configs/camera_params/down.yaml"

  vio_imu:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
      - /dev/:/dev/
    env_file:
      - ./stack.env
    command: bash -c "waitForTime && roslaunch mrs_icm_imu_driver imu.launch"

  automatic_start:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    env_file:
      - ./stack.env
    command: bash -c "waitForHw && roslaunch mrs_uav_autostart automatic_start.launch"

  uav_status:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    env_file:
      - ./stack.env
    command: bash -c "waitForHw && roslaunch mrs_uav_status acquisition.launch"

  open_vins:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    env_file:
      - ./stack.env
    command: bash -c "waitForHw && roslaunch mrs_robofly_core open_vins.launch"

  rosbag:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - bag_files:/etc/bag_files:consistent
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    env_file:
      - ./stack.env
    command: bash -c "waitForTime && /etc/ctu-mrs/shared_data/record.sh"

  terminal:
    image: ctumrs/mrs_uav_system:robofly
    network_mode: host
    depends_on:
      - shared_data
      - uav_configs
    env_file:
      - ./stack.env
    entrypoint: ["/bin/bash", "-c"]
    volumes:
      - bag_files:/etc/bag_files:consistent
      - shared_data:/etc/ctu-mrs/shared_data:consistent
      - uav_configs:/etc/fly4future/uav_configs:consistent
      - /dev/:/dev/
    command:
      - bash --rcfile /opt/ros/noetic/setup.bash
    privileged: true
    stdin_open: true
    tty: true
