# what controller will be used for the landing
controller: "MpcController"

desired_heading:

  relative_to_pad:
    enabled: false
    heading: 0 # [rad]

stages:

  aligning:
    speed: 0.2    # [m/s]
    height: 1.3   # [m]

  repeating:
    height: 1.3 # [m]

  aborting:
    height: 1.3 # [m]

  descending:
    speed: 0.2    # [m/s]

  landing:
    speed: 0.2          # [m/s]
