volumes:

  shared_data:

  bag_files:

services:

  # will copy data shared between containers form the shared_data container to the shared volume
  shared_data:
    image: klaxalk:5000/robofly:shared_data
    volumes:
      - shared_data:/etc/shared_data:consistent
    command: cp -r /etc/ctu-mrs/shared_data /etc/ctu-mrs

  ros-master:
    image: ctumrs/mrs_uav_system:robofly
    network_mode: host
    depends_on:
      - shared_data
    env_file:
      - ./stack.env
    command: roscore

  ros-time:
    image: ctumrs/mrs_uav_system:robofly
    network_mode: host
    depends_on:
      - ros-master
    env_file:
      - ./stack.env
    command: bash -c "waitForRos && rosparam set use_sim_time false"

  hw_api:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    env_file:
      - ./stack.env
    command: bash -c "waitForTime && roslaunch mrs_uav_px4_api api.launch"

  core:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    env_file:
      - ./stack.env
    command: bash -c "waitForHw && roslaunch mrs_uav_core core.launch platform_config:=`rospack find mrs_uav_deployment`/config/mrs_uav_system/$$UAV_TYPE.yaml custom_config:=/etc/config/custom_config.yaml world_config:=/etc/ctu-mrs/shared_data/world_config.yaml network_config:=/etc/ctu-mrs/shared_data/network_config.yaml"

  camera1:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    devices:
      - /dev/:/dev/
    privileged: true
    env_file:
      - ./stack.env
    command: bash -c "waitForTime && roslaunch libcamera_ros_driver uav.launch custom_config:=/etc/ctu-mrs/shared_data/camera.yaml"

  imu:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
      - /dev/:/dev/
    env_file:
      - ./stack.env
    command: bash -c "waitForTime && roslaunch mrs_icm_imu_driver imu.launch"

  automatic_start:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    env_file:
      - ./stack.env
    command: bash -c "waitForHw && roslaunch mrs_uav_autostart automatic_start.launch"

  rosbag:
    image: ctumrs/mrs_uav_system:robofly
    depends_on:
      - ros-time
    network_mode: host
    volumes:
      - bag_files:/etc/bag_files:consistent
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    env_file:
      - ./stack.env
    command: bash -c "waitForTime && /etc/ctu-mrs/shared_data/record.sh"

  terminal:
    image: ctumrs/mrs_uav_system:robofly
    network_mode: host
    depends_on:
      - shared_data
    env_file:
      - ./stack.env
    entrypoint: ["/bin/bash", "-c"]
    volumes:
      - bag_files:/etc/bag_files:consistent
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    command:
      - source /opt/ros/noetic/setup.bash && /bin/bash
    stdin_open: true
    tty: true
