volumes:

  shared_data:

  uav_custom_files:

  bag_files:

services:

  # will copy session-specific data shared between containers from the shared_data container to a shared volume
  copy_shared_data:
    image: fly4future/robofly:apriltag_tests
    volumes:
      - shared_data:/etc/docker/shared_data:consistent
    command: sh -c "rm -rvf /etc/docker/shared_data/*; mkdir -pv /etc/docker/shared_data; cp -rv /etc/shared_data/* /etc/docker/shared_data/"

  # will copy uav-specific configs, launch files and other files from the uav-specific docker image to a shared volume
  copy_uav_custom_files:
    image: fly4future/uav_custom_files:latest
    volumes:
      - uav_custom_files:/etc/docker/uav_custom_files:consistent
    command: sh -c "rm -rvf /etc/docker/uav_custom_files/*; mkdir -pv /etc/docker/uav_custom_files; cp -rv /etc/uav_custom_files/${UAV_TYPE}/${UAV_ID}/* /etc/docker/uav_custom_files/"

  # starts roscore
  # this is the first container in the ROS pipeline
  roscore:
    image: ctumrs/mrs_uav_system:robofly
    network_mode: host
    depends_on:
      - copy_uav_custom_files
    env_file:
      - ./stack.env
    command: roscore

  # starts the camera drivers
  cameras:
    image: ctumrs/mrs_uav_system:robofly
    network_mode: host
    volumes:
      - uav_custom_files:/etc/docker/uav_custom_files:consistent
    devices:
      - /dev/:/dev/
    privileged: true
    env_file:
      - ./stack.env
    command: bash -c "waitForRos && roslaunch /etc/docker/uav_custom_files/launch_files/cameras.launch throttled_rate:=5.0"

  apriltag_bottom:
    image: ctumrs/mrs_uav_system:robofly
    network_mode: host
    depends_on:
      - copy_shared_data
    volumes:
      - shared_data:/etc/docker/shared_data:consistent
    env_file:
      - ./stack.env
    command: bash -c "waitForRos && roslaunch /etc/docker/shared_data/apriltag_detector.launch custom_config:=/etc/docker/shared_data/apriltag.yaml camera_node:=camera_down_throttled image_topic:=image_raw"

  # this container can be used to access a terminal with ROS inside the compose session
  terminal:
    image: ctumrs/mrs_uav_system:robofly
    network_mode: host
    depends_on:
      - copy_shared_data
      - copy_uav_custom_files
    env_file:
      - ./stack.env
    entrypoint: ["/bin/bash", "-c"]
    volumes:
      - shared_data:/etc/docker/shared_data:consistent
      - uav_custom_files:/etc/docker/uav_custom_files:consistent
      - /dev/:/dev/
      - bag_files:/etc/bag_files:consistent
    command:
      - bash --rcfile /opt/ros/noetic/setup.bash
    privileged: true
    stdin_open: true
    tty: true
