mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    # available in mrs_uav_state_estimators: gps_garmin, gps_baro, rtk, aloam, ground_truth, dummy
    state_estimators: [
      "open_vins",
    ]

    initial_state_estimator: "open_vins" # will be used as the first state estimator

  uav_manager:

    takeoff:

      takeoff_height: 1.0 # [m]

      during_takeoff:
        controller: "Se3Controller"

      after_takeoff:
        controller: "Se3Controller"

    midair_activation:

      after_activation:
        controller: "Se3Controller"
        tracker: "MpcTracker"
