mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    # available in mrs_uav_state_estimators: gps_garmin, gps_baro, rtk, aloam, ground_truth, dummy
    state_estimators: [
    "open_vins",
    "vins_kickoff",
    ]

    initial_state_estimator: "vins_kickoff" # will be used as the first state estimator

  uav_manager:

    landing:

      # those two must apply simultaneously
      landing_cutoff_mass_factor:  0.75 # how much lighter does the drone appear to be?
      landing_cutoff_timeout:  0.5 # [s] how long does the throttle has to be below the mass factor

    takeoff:

      during_takeoff:
        controller: "MpcController"

      after_takeoff:
        controller: "MpcController"

  control_manager:

    safety:

      # emergency landing (still feedback)
      eland:

        cutoff_mass_factor:  0.75 # how much lighter does the drone appear to be?
        cutoff_timeout:  0.5 # [s] how long does the throttle has to be below the mass factor
