# Don't change the volume names without also changing them in up.sh
volumes:

  # Going to be filled with the contents of the
  #       ./shared_data/
  # folder.
  shared_data:

  # Going to be filled with the workspace built by
  #       ../colcon_workspace_builder/
  # folder.
  colcon_workspace:

  bag_files:

services:

  # this container primes the shared volumes and allows the content to be place in them
  init:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    volumes:
      - shared_data:/etc/docker/shared_data:consistent
      - colcon_workspace:/etc/docker/colcon_workspace:consistent

  # zenoh router
  zenoh:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    volumes:
      - shared_data:/etc/docker/shared_data
    env_file:
      - ./stack.env
    command: bash -c "export ZENOH_ROUTER_CONFIG_URI=/opt/ros/jazzy/share/mrs_uav_deployment/config/zenoh/uav_router.json5; ros2 run rmw_zenoh_cpp rmw_zenohd"

  camera_front:
    image: ctumrs/libcamera_ros_driver:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    volumes:
      - /dev/:/dev/
      - shared_data:/etc/docker/shared_data
    privileged: true
    env_file:
      - ./stack.env
    command: bash -c "ros2 launch libcamera_ros_driver camera.launch.py custom_config:=/etc/docker/shared_data/config/front/camera_front.yaml camera_name:=front calib_url:=file:///etc/docker/shared_data/config/front/roscalib.yaml"

  camera_down:
    image: ctumrs/libcamera_ros_driver:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    volumes:
      - /dev/:/dev/
      - shared_data:/etc/docker/shared_data
    privileged: true
    env_file:
      - ./stack.env
    command: bash -c "ros2 launch libcamera_ros_driver camera.launch.py custom_config:=/etc/docker/shared_data/config/down/camera_down.yaml camera_name:=down calib_url:=file:///etc/docker/shared_data/config/down/roscalib.yaml"
