volumes:

  catkin_workspace:

  shared_data:

services:

  # will copy session-specific data shared between containers from the shared_data container to a shared volume
  copy_shared_data:
    image: fly4future/robofly:shared_data_vio
    volumes:
      - shared_data:/tmp/docker/shared_data:consistent
    command: sh -c "rm -rvf /tmp/docker/shared_data/*; mkdir -pv /tmp/docker/shared_data; cp -rv /etc/docker/shared_data/* /tmp/docker/shared_data/"

  # will copy user's ROS catkin workspace from the 'transfer' alpine image to a shared volume
  copy_catkin_workspace:
    image: precise_landing:1.0.0
    volumes:
      - catkin_workspace:/tmp/docker/catkin_workspace:consistent
    command: sh -c "rm -rvf /tmp/docker/catkin_workspace/*; mkdir -pv /tmp/docker/catkin_workspace; cp -rv /etc/docker/catkin_workspace/* /tmp/docker/catkin_workspace/"

  # starts the HW API for connecting the MRS UAV System to PX4
  custom_package:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    depends_on:
      - copy_catkin_workspace
      - copy_shared_data
    volumes:
      - catkin_workspace:/etc/docker/catkin_workspace:consistent
      - shared_data:/etc/docker/shared_data:consistent
    env_file:
      - ./stack.env
    command: bash -c "sleep 1 && source /etc/docker/catkin_workspace/devel/setup.bash && waitForRos && roslaunch mrs_precise_landing precise_landing.launch apriltag_config:=/etc/docker/shared_data/precise_landing/apriltag.yaml camera_node:=camera_down_throttled image_topic:=image_raw estimator_config:=/etc/docker/shared_data/precise_landing//landing_estimator.yaml controller_config:=/etc/docker/shared_data/precise_landing//landing_controller.yaml"

  # this container can be used to access a terminal with ROS inside the compose session
  terminal:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    depends_on:
      - copy_catkin_workspace
      - copy_shared_data
    env_file:
      - ./stack.env
    entrypoint: ["/bin/bash", "-c"]
    volumes:
      - catkin_workspace:/etc/docker/catkin_workspace:consistent
      - /dev/:/dev/
    command:
      - bash --rcfile /etc/docker/catkin_workspace/devel/setup.bash
    privileged: true
    stdin_open: true
    tty: true
