volumes:

  shared_data:

services:

  # will copy session-specific data shared between containers from the shared_data container to a shared volume
  copy_shared_data:
    image: fly4future/robofly:apriltag_tests
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    command: sh -c "rm -rvf /etc/ctu-mrs/shared_data/*; mkdir -pv /etc/ctu-mrs/shared_data; cp -rv /etc/shared_data/* /etc/ctu-mrs/shared_data/"

  # starts the HW API for connecting the MRS UAV System to PX4
  apriltag_bottom:
    image: ctumrs/mrs_uav_system:robofly
    network_mode: host
    depends_on:
      - copy_shared_data
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
    env_file:
      - ./stack.env
    command: bash -c "waitForRos && roslaunch /etc/ctu-mrs/shared_data/apriltag_detector.launch custom_config:=/etc/ctu-mrs/shared_data/apriltag.yaml camera_node:=camera_down image_topic:=image_raw"

  # this container can be used to access a terminal with ROS inside the compose session
  terminal:
    image: ctumrs/mrs_uav_system:robofly
    network_mode: host
    depends_on:
      - copy_shared_data
    env_file:
      - ./stack.env
    entrypoint: ["/bin/bash", "-c"]
    volumes:
      - shared_data:/etc/ctu-mrs/shared_data:consistent
      - /dev/:/dev/
    command:
      - bash --rcfile /etc/catkin_workspace/devel/setup.bash
    privileged: true
    stdin_open: true
    tty: true
